{% set name = "python-crfsuite" %}
{% set version = "0.9.7" %}
{% set sha256 = "3b4538d2ce5007e4e42005818247bf43ade89ef08a66d158462e2f7c5d63cee7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - msinttypes  # [win and py27]
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest -v tests
    - conda inspect linkages {{ name }}  # [unix]
    - conda inspect objects {{ name }}   # [osx]

about:
  home: https://github.com/scrapinghub/python-crfsuite
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python binding for CRFsuite
  doc_url: https://python-crfsuite.readthedocs.io/en/latest/
  dev_url: https://github.com/scrapinghub/python-crfsuite

extra:
  recipe-maintainers:
    - wyseguy7
    - ericdill
    - rmax
    - mcs07
