{% set name = "python-crfsuite" %}
{% set version = "0.9.8" %}
{% set sha256 = "0e03cf6eba3628717ccf06dfa0f4a2ba8628860adb174cbfd250a7a4692865a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest -v tests

about:
  home: https://github.com/scrapinghub/python-crfsuite
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python binding for CRFsuite
  doc_url: https://python-crfsuite.readthedocs.io/en/latest/
  dev_url: https://github.com/scrapinghub/python-crfsuite

extra:
  recipe-maintainers:
    - wyseguy7
    - rmax
    - mcs07
