{% set name = "python-crfsuite" %}
{% set version = "0.9.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6eff965ca70567396d822c9a35ea74b0f7edb27d9471524997bdabe7a6da5f5a

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython <3
    - pip
  run:
    - python

test:
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest -v tests

about:
  home: https://github.com/scrapinghub/python-crfsuite
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python binding for CRFsuite
  doc_url: https://python-crfsuite.readthedocs.io/en/latest/
  dev_url: https://github.com/scrapinghub/python-crfsuite

extra:
  recipe-maintainers:
    - wyseguy7
    - rmax
    - mcs07
