# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.9.12"
  cov_fail_under: "91"

package:
  name: python-crfsuite
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/python-crfsuite/python_crfsuite-${{ version }}.tar.gz
  sha256: db37fccc3bd8f0c49c28a7697ca79c89d67b3fd5bf119122866169240ac4c480

build:
  number: 0
  script:
    file: build-pycrfsuite

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - cython
        - python
        - setuptools >=42
  host:
    - cython
    - pip
    - python
    - setuptools >=42
  run:
    - python

tests:
  - python:
      imports: pycrfsuite
      pip_check: true
  - files:
      source:
        - tests/
    requirements:
      run:
        - pytest-cov
    script:
      - coverage run --source=pycrfsuite --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=${{ cov_fail_under }}

about:
  license: MIT
  license_file:
    - LICENSE.txt
    - liblbfgs/COPYING
    - crfsuite/COPYING
  summary: Python binding for CRFsuite
  homepage: https://github.com/scrapinghub/python-crfsuite
  repository: https://github.com/scrapinghub/python-crfsuite
  documentation: https://python-crfsuite.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - wyseguy7
    - rmax
    - mcs07
    - bollwyvl
